/**
 * AUTO-GENERATED by tools/sync-clients.py
 * Source: data/qa-matrix.json
 * Last sync: 2026-04-02T12:30:00+00:00
 *
 * DO NOT EDIT MANUALLY
 * To regenerate: python3 tools/sync-clients.py
 *
 * Flow:
 *   1. python3 data/mongo-extractor.py   # MongoDB → qa-matrix.json
 *   2. python3 tools/sync-clients.py     # qa-matrix.json → this file
 */

import { test as base, expect } from '@playwright/test';

function creds(prefix: string) {
  return {
    email: process.env[`${prefix}_EMAIL`] || '',
    password: process.env[`${prefix}_PASSWORD`] || '',
  };
}

interface ClientConfig {
  name: string;
  baseURL: string;
  loginPath: string;
  credentials: { email: string; password: string };
  config: Record<string, any>;
  coupons?: Array<{ code: string; discount: any }>; // From yom-promotions
  banners?: Array<{ title: string; position: string }>; // From b2b-marketing
  promotions?: Array<any>; // From yom-promotions
}

const clients: Record<string, ClientConfig> = {
  codelpa: {
    name: "Codelpa",
    baseURL: "https://beta-codelpa.solopide.me",
    loginPath: "/login",
    credentials: creds("CODELPA"),
    coupons: [
    { code: "PROMO10", discount: 10 }
  ],
    banners: [
    { title: "Banner Codelpa 1", position: "" },     { title: "Banner Codelpa 2", position: "" }
  ],
    promotions: [{"name": "Promo de Prueba Codelpa", "discount": 5, "active": true}],
    // No conditional tests
    config: {
      anonymousAccess: false,
      currency: "CLP",
      disableCart: false,
      disableCommerceEdit: false,
      enableCoupons: true,
      enableOrderApproval: false,
      hasAllDistributionCenters: true,
      hasStockEnabled: true,
      hidePrices: false,
      hideReceiptType: true,
      purchaseOrderEnabled: true,
    },
  },
  surtiventas: {
    name: "Surtiventas",
    baseURL: "https://surtiventas.solopide.me",
    loginPath: "/auth/jwt/login",
    credentials: creds("SURTIVENTAS"),
    coupons: [
    { code: "SURTI15", discount: 15 }
  ],
    banners: [
    { title: "Promo Banner Surtiventas", position: "" }
  ],
    promotions: [{"name": "Promo Surtiventas", "discount": 8, "active": true}],
    // No conditional tests
    config: {
      anonymousAccess: false,
      currency: "CLP",
      disableCart: false,
      disableCommerceEdit: false,
      editAddress: true,
      enableCoupons: true,
      enableSellerDiscount: true,
      hasMultiUnitEnabled: true,
      hasSingleDistributionCenter: true,
      hasStockEnabled: true,
      hidePrices: false,
      hideReceiptType: false,
      useNewPromotions: true,
    },
  },
};

export default clients;
