/**
 * AUTO-GENERATED by tools/sync-clients.py
 * Source: data/qa-matrix.json
 * Last sync: 2026-04-02T14:10:33.484261+00:00
 *
 * DO NOT EDIT MANUALLY
 * To regenerate: python3 tools/sync-clients.py
 *
 * Flow:
 *   1. python3 data/mongo-extractor.py   # MongoDB → qa-matrix.json
 *   2. python3 tools/sync-clients.py     # qa-matrix.json → this file
 */

import { test as base, expect } from '@playwright/test';

function creds(prefix: string) {
  return {
    email: process.env[`${prefix}_EMAIL`] || '',
    password: process.env[`${prefix}_PASSWORD`] || '',
  };
}

interface ClientConfig {
  name: string;
  baseURL: string;
  loginPath: string;
  credentials: { email: string; password: string };
  config: Record<string, any>;
  coupons?: Array<{ code: string; discount: any }>; // From yom-promotions
  banners?: Array<{ title: string; position: string }>; // From b2b-marketing
  promotions?: Array<any>; // From yom-promotions
  integrations?: { segments: any; overrides: any; userSegments: any }; // From integrations cluster
}

const clients: Record<string, ClientConfig> = {
  codelpa: {
    name: "Codelpa",
    baseURL: "https://codelpa.youorder.me",
    loginPath: "/login",
    credentials: creds("CODELPA"),
    coupons: [],
    banners: [],
    promotions: [],
    integrations: {"segments": [{"name": "B-ANT0325", "code": "", "active": true}, {"name": "B-CAL0325", "code": "", "active": true}, {"name": "B-CON0325", "code": "", "active": true}, {"name": "B-CUR0325", "code": "", "active": true}, {"name": "B-PTO0325", "code": "", "active": true}], "overrides": [{"productId": "", "price": null, "discount": null, "enabled": false}, {"productId": "", "price": null, "discount": null, "enabled": false}, {"productId": "", "price": null, "discount": null, "enabled": false}, {"productId": "", "price": null, "discount": null, "enabled": false}, {"productId": "", "price": null, "discount": null, "enabled": false}], "userSegments": [{"name": "", "segmentId": "5f43917122dad64780fe57ee", "userCount": 0}, {"name": "", "segmentId": "67c644ee48b024c728113118", "userCount": 0}, {"name": "", "segmentId": "67c644ee48b024c728113126", "userCount": 0}, {"name": "", "segmentId": "67c644ee48b024c728113126", "userCount": 0}, {"name": "", "segmentId": "5f43917122dad64780fe57ee", "userCount": 0}]},
    // Conditional tests: C2-E10, C2-E4, C2-E5, C2-E9, C3-E3, C3-E4, C3-E6, C6-E3, P1-12, P2-02, +8 more
    config: {
      anonymousAccess: false,
      anonymousHideCart: true,
      anonymousHidePrice: true,
      "contact.about": "Grupo Codelpa Colores del Pac\u00edfico, es la empresa de pinturas y revestimientos m\u00e1s grande del pa\u00eds, agrupando marcas de pinturas como Ceresita, Sipa, Soquina, Chilcorrof\u00edn, Pinmor y Titanium 2K de Sipa.",
      "contact.branchesContactInformation": [{"address": "Camino Lo Echevers 801, Quilicura", "phone": "+562227262800", "email": "info@codelpa.cl"}],
      "contact.email": "info@codelpa.cl",
      disableCart: false,
      disableCommerceEdit: true,
      disableShowEstimatedDeliveryHour: false,
      editAddress: false,
      enableAskDeliveryDate: false,
      enableCoupons: true,
      enableCreditStateMessage: false,
      enableDialogNoSellReason: false,
      enableInvoicesList: false,
      enableMassiveOrderSend: true,
      enableOrderApproval: true,
      enableOrderValidation: true,
      enableSellerDiscount: true,
      enableTask: true,
      externalAccess: false,
      hasAllDistributionCenters: true,
      hasSingleDistributionCenter: false,
      hasStockEnabled: true,
      hidePrices: false,
      hideReceiptType: true,
      "hooks.cartShoppingHook": false,
      "hooks.getPendingDocumentsHook": false,
      "hooks.shippingHook": true,
      "hooks.stockHook": true,
      "hooks.updateTrafficLightHook": false,
      inMaintenance: false,
      includeTaxRateInPrices: false,
      lazyLoadingPrices: false,
      ordersRequireAuthorization: false,
      ordersRequireVerification: false,
      "packagingInformation.hidePackagingInformationB2B": false,
      "packagingInformation.hideSingleItemPackagingInformationB2B": true,
      "packagingInformation.ignoreUnitOnPackInformationB2B": false,
      "payment.enableNewPaymentModule": false,
      pendingDocuments: true,
      pointsEnabled: false,
      productVariability: "none",
      purchaseOrderEnabled: true,
      "shoppingDetail.lastOrder": true,
      showEmptyCategories: false,
      showMinOne: false,
      "synchronization.enableSyncImages": true,
      "taxes.showSummary": true,
      "taxes.taxRate": 0,
      "taxes.useTaxRate": false,
      useMobileGps: true,
      useMongoPricing: true,
      weightInfo: false,
    },
  },
  "codelpa-peru": {
    name: "Codelpa Peru",
    baseURL: "https://codelpa-peru.youorder.me",
    loginPath: "/auth/jwt/login",
    credentials: creds("CODELPA-PERU"),
    coupons: [],
    banners: [],
    promotions: [],
    integrations: {"segments": [{"name": "BASE", "code": "", "active": true}, {"name": "PINA032025", "code": "", "active": true}, {"name": "PINTURERIA ESTRAT\u00c9GICA 03-2025", "code": "", "active": true}, {"name": "PINTURERIA VIP 03-2025", "code": "", "active": true}], "overrides": [{"productId": "", "price": null, "discount": null, "enabled": false}, {"productId": "", "price": null, "discount": null, "enabled": false}, {"productId": "", "price": null, "discount": null, "enabled": false}, {"productId": "", "price": null, "discount": null, "enabled": false}, {"productId": "", "price": null, "discount": null, "enabled": false}], "userSegments": [{"name": "", "segmentId": "69810d5af95f93940cb6ec49", "userCount": 0}, {"name": "", "segmentId": "69810d5af95f93940cb6ec49", "userCount": 0}, {"name": "", "segmentId": "69810d5af95f93940cb6ec49", "userCount": 0}, {"name": "", "segmentId": "69810d5af95f93940cb6ec48", "userCount": 0}, {"name": "", "segmentId": "69810d5af95f93940cb6ec49", "userCount": 0}]},
    // Conditional tests: C2-E9, P1-03, P2-03, P3-01, P3-02, V1-E4
    config: {
      anonymousAccess: false,
      anonymousHideCart: false,
      anonymousHidePrice: false,
      "blockedClientAlert.enableBlockedClientAlert": false,
      businessUnits: [],
      "commerce.enableCreateCommerce": false,
      disableCart: false,
      disableCommerceEdit: false,
      disableObservationInput: false,
      disablePayments: false,
      disableShowEstimatedDeliveryHour: false,
      "discountTypes.discountTypesList": [],
      "discountTypes.enableOrderDiscountType": false,
      "discountTypes.enableProductDiscountType": false,
      editAddress: true,
      enableAskDeliveryDate: false,
      enableBetaButtons: false,
      enableChooseSaleUnit: false,
      enableCoupons: true,
      enableCreditNotes: false,
      enableDialogNoSellReason: false,
      enableDistributionCentersSelector: false,
      enableInvoicesList: false,
      enableNewUI: false,
      enableOrderApproval: false,
      enableOrderValidation: false,
      enablePaymentDocumentsB2B: false,
      enablePayments: false,
      enablePaymentsCollection: false,
      enablePriceOracle: false,
      enableSellerDiscount: false,
      enableTask: false,
      externalAccess: false,
      filterGroupedSuggestionsBy: [],
      "footerCustomContent.useFooterCustomContent": false,
      hasAllDistributionCenters: false,
      hasMultiUnitEnabled: false,
      hasMultipleBusinessUnit: false,
      hasNoSaleFilter: false,
      hasSingleDistributionCenter: true,
      hasStockEnabled: false,
      hasTransferPaymentType: false,
      hasTransportCode: false,
      hasVoucherPrinterEnabled: false,
      hidePrices: false,
      hideReceiptType: false,
      "hooks.cartShoppingHook": false,
      "hooks.getPendingDocumentsHook": false,
      "hooks.shippingHook": false,
      "hooks.stockHook": false,
      "hooks.updateTrafficLightHook": false,
      inMaintenance: false,
      includeTaxRateInPrices: false,
      lazyLoadingPrices: false,
      limitAddingByStock: false,
      mustHaveOverride: false,
      orderObservations: [],
      ordersRequireAuthorization: false,
      ordersRequireVerification: false,
      "packagingInformation.hidePackagingInformationB2B": true,
      "packagingInformation.hideSingleItemPackagingInformationB2B": true,
      "packagingInformation.ignoreUnitOnPackInformationB2B": false,
      "payment.balances": [],
      "payment.enableNewPaymentModule": true,
      "payment.requiresFullPayment": false,
      paymentsWithoutAccount: false,
      pendingDocuments: false,
      pointsEnabled: false,
      priceRoundingDecimals: 2,
      productVariability: "none",
      purchaseOrderEnabled: false,
      shareOrderNewDesign: false,
      "shoppingDetail.lastOrder": false,
      showEmptyCategories: false,
      showMinOne: false,
      "synchronization.backgroundSyncList": [],
      "synchronization.enableBackgroundSendOrders": false,
      "synchronization.enableBackgroundSync": false,
      "synchronization.enableSyncImages": false,
      "taxes.showSummary": false,
      "taxes.taxRate": 0,
      "taxes.useTaxRate": false,
      uploadOrderFileWithMinUnits: false,
      useMobileGps: false,
      useMongoPricing: false,
      useNewPromotions: false,
      validatePaymentFromAdmin: false,
      weightInfo: false,
    },
  },
};

export default clients;
